krb5_admin stream tcp wait root /usr/libexec/prefork prefork /usr/bin/knc -iS /run/krb5_hostd
krb5_admin stream tcp6 wait root /usr/libexec/prefork prefork /usr/bin/knc -iS /run/krb5_hostd
/run/krb5_hostd stream unix wait root /usr/libexec/prefork prefork /scripts/krb5-hostd-prefork
bifrost stream tcp wait root /usr/libexec/prefork prefork /usr/bin/knc -iS /run/bifrost/hostd.sock
bifrost stream tcp6 wait root /usr/libexec/prefork prefork /usr/bin/knc -iS /run/bifrost/hostd.sock
/run/bifrost/hostd.sock stream unix wait root /usr/bin/bifrost bifrost hostd
