krb5_admin	stream	tcp    wait root /usr/libexec/prefork	prefork /usr/bin/knc -iS /run/krb5_admin
krb5_admin	stream	tcp6   wait root /usr/libexec/prefork	prefork /usr/bin/knc -iS /run/krb5_admin
/run/krb5_admin stream	unix   wait root /usr/libexec/prefork	prefork -n 5 -N 20 /usr/sbin/krb5_admind -P
bifrost		stream	tcp    wait root /usr/bin/bifrost	bifrost kdcd
bifrost		stream	tcp6   wait root /usr/bin/bifrost	bifrost kdcd
