[supervisord]
user=root
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:kdc]
command=/usr/sbin/kdc
autorestart=true
autostart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:kpasswdd]
command=/usr/sbin/kpasswdd
autorestart=true
autostart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:ipropd]
command=/scripts/ipropd
autorestart=true
autostart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:inetd]
command=/usr/sbin/inetd -i
autorestart=true
autostart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:syslogd]
command=/usr/sbin/syslogd -n
autorestart=true
autostart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
